
package gui;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author ALEX
 */
public class GameFondo extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    static final int UNIT_SIZE = 20;


    public GameFondo() {

        initComponents();
    }

    @Override
    public void paint(Graphics graphics) {
        super.paint(graphics);  //regrafica

        for (int i = 0; i <= 25; i++) {
            for (int j = 0; j <= 25; j++) {
                // Alternar colores según la suma de índices
                if ((i + j) % 2 == 0) {
                    graphics.setColor(new Color(0, 100, 0));
                } else {
                    graphics.setColor(new Color(0, 128, 0));
                }

                graphics.fillRect(i * UNIT_SIZE, j * UNIT_SIZE, UNIT_SIZE, UNIT_SIZE);

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
